statistiques/apps/main/urls.py
""" apps/main/urls.py """

from django.urls import path

from . import views

app_name = 'main'
urlpatterns = [
    path('', views.home, name='home'),
    path('<int:pk>/', views.update, name='update'),
]

statistiques/apps/main/models.py
""" apps/main/models.py """

from django.db import models


class Monk(models.Model):
    """ Moine model. """
    name = models.CharField(
        max_length=25,
        db_column='nom',
    )
    birth = models.DateField(
        db_column='naissance',
    )
    entry = models.DateField(
        db_column='entree',
    )
    rank = models.SmallIntegerField(
        db_column='rang',
    )
    habit = models.DateField(
        db_column='prise_habit',
    )
    temporary_profession = models.DateField(
        db_column='prof_temp',
    )
    perpetual_profession = models.DateField(
        db_column='prof_perpet',
    )
    ordination = models.DateField(
        db_column='ordination',
    )

    class Meta:
        managed = False
        db_table = 'Moines'

    def __str__(self):
        return self.name

statistiques/apps/main/forms.py
""" apps/main/forms.py """

from django import forms

from tempus_dominus.widgets import DatePicker

from .models import Monk


class MonkForm(forms.ModelForm):
    """ Form for Monk. """
    name = forms.CharField(
        max_length=255,
        label='Nom :',
        label_suffix='',
    )
    birth = forms.DateField(
        required=False,
        label='Date de naissance :',
        label_suffix='',
        input_formats=[
            '%d/%m/%Y',
        ],
        widget=DatePicker(
            options={
                'format': 'DD/MM/YYYY',
            }
        ),
    )
    entry = forms.DateField(
        required=False,
        label='Entrée :',
        label_suffix='',
        input_formats=[
            '%d/%m/%Y',
        ],
        widget=DatePicker(
            options={
                'format': 'DD/MM/YYYY',
            },
        ),
    )
    habit = forms.DateField(
        required=False,
        label='Prise d\'habit :',
        label_suffix='',
        input_formats=[
            '%d/%m/%Y',
        ],
        widget=DatePicker(
            options={
                'format': 'DD/MM/YYYY',
            }
        ),
    )
    temporary_profession = forms.DateField(
        required=False,
        label='Profession temporaire :',
        label_suffix='',
        input_formats=[
            '%d/%m/%Y',
        ],
        widget=DatePicker(
            options={
                'format': 'DD/MM/YYYY',
            }
        ),
    )
    perpetual_profession = forms.DateField(
        required=False,
        label='Profession perpétuelle :',
        label_suffix='',
        input_formats=[
            '%d/%m/%Y',
        ],
        widget=DatePicker(
            options={
                'format': 'DD/MM/YYYY',
            }
        ),
    )
    ordination = forms.DateField(
        required=False,
        label='Ordination :',
        label_suffix='',
        input_formats=[
            '%d/%m/%Y',
        ],
        widget=DatePicker(
            options={
                'format': 'DD/MM/YYYY',
            }
        ),
    )

    class Meta:
        model = Monk
        fields = [
            'name',
            'birth',
            'entry',
            'habit',
            'temporary_profession',
            'perpetual_profession',
            'ordination',
        ]

statistiques/apps/main/views.py
""" apps/statistiques/views.py """


from datetime import date
from statistics import mean
import os
import numpy
from matplotlib import pyplot

from django.conf import settings
from django.http import HttpResponseRedirect
from django.shortcuts import render, reverse
from .forms import MonkForm
from .models import Monk


def home(request):
    """ Home page of statistiques. """
    list_of_monks = Monk.objects.all().order_by('entry')
    postulants = len(
        Monk.objects
        .filter(habit__isnull=True)
    )
    novices = len(
        Monk.objects
        .filter(habit__isnull=False)
        .filter(temporary_profession__isnull=True)
    )
    tempo = len(
        Monk.objects
        .filter(temporary_profession__isnull=False)
        .filter(perpetual_profession__isnull=True)
    )
    perpetual = len(
        Monk.objects
        .filter(perpetual_profession__isnull=False)
    )
    priests = len(
        Monk.objects
        .filter(ordination__isnull=False)
    )

    # Average age
    ages = []
    monks = Monk.objects.all()
    for index, monk in enumerate(monks):
        ages.append((date.today() - monk.birth).days / 365)

    # Histogram:
    hist, bin_edges = numpy.histogram(
        ages,
        bins=[10, 20, 30, 40, 50, 60, 70, 80, 90, 100]
    )
    pyplot.figure(figsize=[10, 5])
    result = pyplot.bar([i + 5 for i in bin_edges[:-1]],
                        hist, width=9, color='orange')
    for i, patch in enumerate(list(result)):
        if hist[i] > 0:
            pyplot.text(bin_edges[i] + 5, hist[i] + 1, hist[i],
                        ha='center', va='bottom')
    pyplot.xlim(min(bin_edges), max(bin_edges))
    pyplot.xlabel('Âge', fontsize=10)
    pyplot.ylabel('Nombre de moines', fontsize=10)
    pyplot.xticks(
        numpy.arange(
            min(bin_edges),
            max(bin_edges),
            10),
        fontsize=10
    )
    pyplot.yticks(
        numpy.arange(
            0,
            max(hist) + 5,
            5),
        fontsize=10
    )
    average_age = mean(ages)
    pyplot.text(
        20,
        max(hist) - 5,
        'Moyenne : {:.2f} ans'.format(average_age),
        fontsize=10
    )
    pyplot.savefig(
        os.path.join(settings.BASE_DIR, 'static/img/histogram.svg'),
        format='svg',
    )

    return render(
        request,
        'main/home.html',
        {
            'list_of_monks': list_of_monks,
            'monks': len(list_of_monks),
            'postulants': postulants,
            'novices': novices,
            'tempo': tempo,
            'perpetual': perpetual,
            'priests': priests,
        }
    )


def update(request, **kwargs):
    """ Update a monk. """
    monk = Monk.objects.get(pk=kwargs['pk'])

    if request.method == 'POST':
        form = MonkForm(request.POST, instance=monk)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(
                reverse('main:home')
            )

    else:
        form = MonkForm(instance=monk)

    return render(
        request,
        'main/form.html',
        {
            'form': form,
            'monk': monk,
        }
    )

statistiques/apps/main/templates/main/form.html
{% extends 'main.html' %}

{% load widget_tweaks %}

{% block content %}
    <h2 class="mb-2 green font-weight-bold">{{ monk }}</h2>

    <a href={% url 'main:home' %} class="mb-4">Retour à la liste</a>

    <form class="d-flex flex-column align-items-center w-100 mb-3" method="post" novalidate>

        {% csrf_token %}

        <!-- Name -->
        <div class="form-group">
            {{ form.name.label_tag }}

            {% if form.is_bound %}
                {% if form.name.errors %}
                    {% render_field form.name class="form-control is-invalid" %}
                    {% for error in form.name.errors %}
                        <div class="invalid-feedback" style="display: block;">
                            {{ error }}
                        </div>
                    {% endfor %}
                {% else %}
                    {% render_field form.name class="form-control is-valid" %}
                {% endif %}
            {% else %}
                {% render_field form.name class="form-control" %}
            {% endif %}

            {% if form.name.help_text %}
                <small class="form-text text-muted">
                    {{ form.name.help_text }}
                </small>
            {% endif %}
        </div>

        <!-- Birth -->
        <div class="form-group">
            {{ form.birth.label_tag }}

            {% if form.is_bound %}
                {% if form.birth.errors %}
                    {% render_field form.birth class="form-control is-invalid" %}
                    {% for error in form.birth.errors %}
                        <div class="invalid-feedback" style="display: block;">
                            {{ error }}
                        </div>
                    {% endfor %}
                {% else %}
                    {% render_field form.birth class="form-control is-valid" %}
                {% endif %}
            {% else %}
                {% render_field form.birth class="form-control" %}
            {% endif %}

            {% if form.birth.help_text %}
                <small class="form-text text-muted">
                    {{ form.birth.help_text }}
                </small>
            {% endif %}
        </div>

        <!-- Entry -->
        <div class="form-group">
            {{ form.entry.label_tag }}

            {% if form.is_bound %}
                {% if form.entry.errors %}
                    {% render_field form.entry class="form-control is-invalid" %}
                    {% for error in form.entry.errors %}
                        <div class="invalid-feedback" style="display: block;">
                            {{ error }}
                        </div>
                    {% endfor %}
                {% else %}
                    {% render_field form.entry class="form-control is-valid" %}
                {% endif %}
            {% else %}
                {% render_field form.entry class="form-control" %}
            {% endif %}

            {% if form.entry.help_text %}
                <small class="form-text text-muted">
                    {{ form.entry.help_text }}
                </small>
            {% endif %}
        </div>

        <!-- Habit -->
        <div class="form-group">
            {{ form.habit.label_tag }}

            {% if form.is_bound %}
                {% if form.habit.errors %}
                    {% render_field form.habit class="form-control is-invalid" %}
                    {% for error in form.habit.errors %}
                        <div class="invalid-feedback" style="display: block;">
                            {{ error }}
                        </div>
                    {% endfor %}
                {% else %}
                    {% render_field form.habit class="form-control is-valid" %}
                {% endif %}
            {% else %}
                {% render_field form.habit class="form-control" %}
            {% endif %}

            {% if form.habit.help_text %}
                <small class="form-text text-muted">
                    {{ form.habit.help_text }}
                </small>
            {% endif %}
        </div>

        <!-- Temporary profession -->
        <div class="form-group">
            {{ form.temporary_profession.label_tag }}

            {% if form.is_bound %}
                {% if form.temporary_profession.errors %}
                    {% render_field form.temporary_profession class="form-control is-invalid" %}
                    {% for error in form.temporary_profession.errors %}
                        <div class="invalid-feedback" style="display: block;">
                            {{ error }}
                        </div>
                    {% endfor %}
                {% else %}
                    {% render_field form.temporary_profession class="form-control is-valid" %}
                {% endif %}
            {% else %}
                {% render_field form.temporary_profession class="form-control" %}
            {% endif %}

            {% if form.temporary_profession.help_text %}
                <small class="form-text text-muted">
                    {{ form.temporary_profession.help_text }}
                </small>
            {% endif %}
        </div>

        <!-- Perpetual profession -->
        <div class="form-group">
            {{ form.perpetual_profession.label_tag }}

            {% if form.is_bound %}
                {% if form.perpetual_profession.errors %}
                    {% render_field form.perpetual_profession class="form-control is-invalid" %}
                    {% for error in form.perpetual_profession.errors %}
                        <div class="invalid-feedback" style="display: block;">
                            {{ error }}
                        </div>
                    {% endfor %}
                {% else %}
                    {% render_field form.perpetual_profession class="form-control is-valid" %}
                {% endif %}
            {% else %}
                {% render_field form.perpetual_profession class="form-control" %}
            {% endif %}

            {% if form.perpetual_profession.help_text %}
                <small class="form-text text-muted">
                    {{ form.perpetual_profession.help_text }}
                </small>
            {% endif %}
        </div>

        <!-- Ordination -->
        <div class="form-group">
            {{ form.ordination.label_tag }}

            {% if form.is_bound %}
                {% if form.ordination.errors %}
                    {% render_field form.ordination class="form-control is-invalid" %}
                    {% for error in form.ordination.errors %}
                        <div class="invalid-feedback" style="display: block;">
                            {{ error }}
                        </div>
                    {% endfor %}
                {% else %}
                    {% render_field form.ordination class="form-control is-valid" %}
                {% endif %}
            {% else %}
                {% render_field form.ordination class="form-control" %}
            {% endif %}

            {% if form.ordination.help_text %}
                <small class="form-text text-muted">
                    {{ form.ordination.help_text }}
                </small>
            {% endif %}
        </div>

        <!-- Validation -->
        <div class="d-flex justify-content-center">
            <a href={% url 'main:home' %} class="btn btn-primary mx-3">Annuler</a>
            <button type="submit" class="btn btn-success mx-3">Valider</button>
        </div>
    </form>
{% endblock content %}

statistiques/apps/main/templates/main/home.html
{% extends 'main.html' %}

{% load static %}

{% block content %}
    <h1 class="mt-5">Abbaye Saint-Joseph de Clairval</h1>
    <h4 class="mb-5 green">Statistiques</h4>

    <div class="d-flex flex-column align-items-center mb-5">
        <div class="col-8">
            <table class="table table-sm table-bordered">
                <tr>
                    <td class="font-weight-bold">Moines :</td>
                    <td class="text-center">{{ monks }}</td>
                </tr>
                <tr>
                    <td class="font-weight-bold">Prêtres :</td>
                    <td class="text-center">{{ priests }}</td>
                </tr>
                <tr>
                    <td class="font-weight-bold">Profès perpétuels :</td>
                    <td class="text-center">{{ perpetual }}</td>
                </tr>
                <tr>
                    <td class="font-weight-bold">Profès temporaires :</td>
                    <td class="text-center">{{ tempo }}</td>
                </tr>
                <tr>
                    <td class="font-weight-bold">Novices :</td>
                    <td class="text-center">{{ novices }}</td>
                </tr>
                <tr>
                    <td class="font-weight-bold">Postulants :</td>
                    <td class="text-center">{{ postulants }}</td>
                </tr>
            </table>
        </div>

        <img src={% static 'img/histogram.svg' %} alt="Missing histogram" class="mb-3">
    </div>

    <table class="table table-sm table-bordered">
        <tr>
            <th class="col-2">Moine</th>
            <th class="col-1">Naissance</th>
            <th class="col-1">Entrée</th>
            <th class="col-1">Prise d'habit</th>
            <th class="col-1">Prof. temporaire</th>
            <th class="col-1">Prof. perpétuelle</th>
            <th class="col-1">Ordination</th>
            <th class="col-1"></th>
        </tr>
        {% for monk in list_of_monks %}
            <tr>
                <td>{{ monk }}</td>
                <td class="text-center">{{ monk.birth|date:'d/m/Y' }}</td>
                <td class="text-center">{{ monk.entry|date:'d/m/Y' }}</td>
                <td class="text-center">{{ monk.habit|date:'d/m/Y' }}</td>
                <td class="text-center">{{ monk.temporary_profession|date:'d/m/Y' }}</td>
                <td class="text-center">{{ monk.perpetual_profession|date:'d/m/Y' }}</td>
                <td class="text-center">{{ monk.ordination|date:'d/m/Y' }}</td>
                <td class="text-center"><a href={% url 'main:update' monk.pk %}>Modifier</a></td>
            </tr>
        {% endfor %}
    </table>
{% endblock content %}